version: "3"
services:
  node:
    build: ../../server
    container_name: tripapps_node
    environment:
      PORT: 5000
      MONGODB_URL: mongodb://db:27017/tripapps
  nextjs:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.nextjs
    container_name: tripapps_nextjs
    depends_on:
      - node
    environment:
      BUILDTIME_API_URL: http://node:5000
      NEXT_PUBLIC_API_URL: /api
  nginx:
    container_name: tripapps_nginx
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.nginx
    depends_on:
      - nextjs
    ports:
      - 80:80
networks:
  default:
    name: tripapps_network
    driver: bridge
