pipeline {
  agent any
  environment {
    DockerHubCredentialsID = 'dockerhub'
    TripAppsVpsCredentialsID = 'tripapps-vps-ssh'
    DockerHubRepo = 'jadhamwi21/tripapps'
    TripAppsDockerNetwork = 'tripapps_network'
    TripAppsVpsIpAddress = '212.227.47.195'
    NginxPort = 80
    NextjsServerSideApiUrl = "http://node:5000"
    NextjsClientSideApiUrl = "/api"
  }
  stages {
    stage("build:nextjs") {
      steps {
          dir("./client"){
            script {
              docker.withTool("docker") {
                def dockerImage = docker.build("$DockerHubRepo:nextjs","-f Dockerfile.nextjs .")
                docker.withRegistry('',DockerHubCredentialsID){
                  dockerImage.push();
                }
              }
            }
          }
      }
    }
    stage("build:nginx") {

      steps {
          dir("./client"){
            script {
              docker.withTool("docker") {
                def dockerImage = docker.build("$DockerHubRepo:nginx","-f Dockerfile.nginx .")
                docker.withRegistry('',DockerHubCredentialsID){
                  dockerImage.push();
                }
              }
            }
          }
      }
    }
    stage("deploy") {
      steps {
        sshagent([TripAppsVpsCredentialsID]) {
          // Nginx Deployment
          script {
            def COMMANDS = """
            docker pull $DockerHubRepo:nginx;
            docker rm --force tripapps-nginx 2> /dev/null || echo 'No Container';
            docker run --hostname nginx --restart always -p $NginxPort:$NginxPort --name tripapps-nginx -d --network $TripAppsDockerNetwork $DockerHubRepo:nginx;
            """
            sh "ssh -o StrictHostKeyChecking=no $TripAppsVpsIpAddress -l jad $COMMANDS"
          }
          // Nextjs Deployment
          script {
            def COMMANDS = """
            docker pull $DockerHubRepo:nextjs;
            docker rm --force tripapps-nextjs 2> /dev/null || echo 'No Container';
            docker run --hostname nextjs --name tripapps-nextjs -e SERVER_API_URL=$NextjsServerSideApiUrl -e NEXT_PUBLIC_API_URL=$NextjsClientSideApiUrl -d --network $TripAppsDockerNetwork $DockerHubRepo:nextjs;
            """
            sh "ssh -o StrictHostKeyChecking=no $TripAppsVpsIpAddress -l jad $COMMANDS"
          }
        }
      }
    }
  }
  post {
    always {
      sh 'docker logout'
    }
  }
}