pipeline {
  agent any
  environment {
    DockerHubCredentialsID = 'dockerhub'
    TripAppsVpsCredentialsID = 'tripapps-vps-ssh'
    DockerHubRepo = 'jadhamwi21/tripapps'
    TripAppsDockerNetwork = 'tripapps_network'
    TripAppsVpsIpAddress = '212.227.47.195'
    MongodbUrl = "mongodb://db:27017/tripapps"
    ScrapersApiUrl = "http://scrapers:8000"
  }
  stages {
    stage("build") {
      steps {
        dir("./cli") {
          script {
            docker.withTool('docker') {
              def dockerImage = docker.build "$DockerHubRepo:cli"
              docker.withRegistry('', DockerHubCredentialsID) {
                dockerImage.push()
              }
            }
          }
        }
      }
    }
    stage("deploy") {
      steps {
        sshagent([TripAppsVpsCredentialsID]) {
          script {
            def COMMANDS = """
            docker pull $DockerHubRepo:cli;
            docker rm --force tripapps-cli 2> /dev/null || echo 'No Container';
            docker run --name tripapps-cli -e MONGODB_URL=$MongodbUrl -e SCRAPERS_API_URL=$ScrapersApiUrl -d --network $TripAppsDockerNetwork $DockerHubRepo:cli;
            """
            sh "ssh -o StrictHostKeyChecking=no $TripAppsVpsIpAddress -l jad $COMMANDS"
          }
        }
      }
    }
  }
  post {
    always {
      sh 'docker logout'
    }
  }
}