pipeline {
  agent any
  environment {
    DockerHubCredentialsID = 'dockerhub'
    TripAppsVpsCredentialsID = 'tripapps-vps-ssh'
    DockerHubRepo = 'jadhamwi21/tripapps'
    TripAppsDockerNetwork = 'tripapps_network'
    TripAppsVpsIpAddress = '212.227.47.195'
  }
  stages {
    stage("build") {
      steps {
        dir("./scrapers") {
          script {
            docker.withTool('docker') {
              def dockerImage = docker.build "$DockerHubRepo:scrapers"
              docker.withRegistry('', DockerHubCredentialsID) {
                dockerImage.push()
              }
            }
          }
        }
      }
    }
    stage("deploy") {
      steps {
        sshagent([TripAppsVpsCredentialsID]) {
          script {
            def COMMANDS = """
            docker pull $DockerHubRepo:scrapers;
            docker rm --force tripapps-scrapers 2> /dev/null || echo 'No Container';
            docker run --name tripapps-scrapers --hostname scrapers -d --network $TripAppsDockerNetwork $DockerHubRepo:scrapers;
            """
            sh "ssh -o StrictHostKeyChecking=no $TripAppsVpsIpAddress -l jad $COMMANDS"
          }
        }
      }
    }
  }
  post {
    always {
      sh 'docker logout'
    }
  }
}